### ISSUE TITLE
[Bug] Inject Context Error

### ISSUE THREAD

**Issue by soulFood5632** [RailtownAI/railtracks#910]
### Description

When running the API found in https://github.com/[RailtownAI/resume-tuner](https://github.com/RailtownAI/resume-tuner) we ran into a curious error with the `prompt_injection`. I am not super sure what the cause but I think it could be os and version dependent. 

### Reproducing Steps (include code examples if applicable)

Check out https://github.com/[RailtownAI/resume-tuner](https://github.com/RailtownAI/resume-tuner). Run the app the locally and call the job-description API for any job. 

### Operating System

Apple

### Python Version

3.10

**Comment by CoronRing** [comment]
The cause is likely #1116. by likely I mean it is 100% caused by #1116, but I am not sure if there are other factors beyond #1116 that amplify/also trigger crash. 

Raw HTML goes in as the user message, so inline CSS, JSON-LD, JS objects, and Handlebars/Angular templates all get parsed as str.format fields.

Some runs on sample resume:

| Fragment | Outcome |
| --- | --- |
| `.jd{margin:0;padding:1rem}` , JSON-LD, `{jobs:[{id:1}]}` | `ValueError` → **swallowed**, message left untemplated, request succeeds |
| `(a)=>{ return a.map(x=>x.id) }` | `AttributeError: 'str' object has no attribute 'map(x=>x'` → **crash** |
| ``` `{{#each jobs}}`<br><br>`{{title}}` / `{{`<br><br>`job.title }}``` ` | **silently rewritten** to `{#each`<br><br>`jobs}{title}` / `{ job.title }`<br><br>before the model sees it |

**Comment by CoronRing** [comment]
Addressed by https://github.com/RailtownAI/railtracks/pull/1386
